version: '2'
services:
  postgrest:
    image: postgrest/postgrest
    ports:
      - '3000:3000'
    environment:
      - 'PGRST_DB_URI=postgres://lovegood:password@postgres:5432/quibbler'
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=lovegood
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=quibbler
      - POSTGRES_USER=lovegood
      - POSTGRES_PASSWORD=password
    volumes:
      - './data/quibbler:/var/lib/postgresql/data'
    ports:
      - '6543:5432'
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - 'API_URL=http://localhost:3000/'
    ports:
      - '8080:8080'
