#!/bin/bash
export PATH=/root/.pyenv/shims:/root/.pyenv/bin:"$PATH"
cd "$(dirname "$0")"
source ../environment/bin/activate
python scrape.py \
	4threvolutionarywar.wordpress.com \
	abeldanger.net \
	abovetopsecret.com \
	activistpost.com \
	ahtribune.com \
	allnewspipeline.com \
	americanlookout.com \
	americanthinker.com \
	americasfreedomfighters.com \
	ammoland.com \
	amren.com \
	amtvmedia.com \
	ancient-code.com \
	anonews.co \
	anonhq.com \
	antiwar.com \
	asia-pacificresearch.com \
	assassinationscience.com \
	baltimoregazette.com \
	barenakedislam.com \
	beforeitsnews.com \
	bignuggetnews.com \
	blackagendareport.com \
	blacklistednews.com \
	breitbart.com \
	canadafreepress.com \
	centerforsecuritypolicy.org \
	christianfightback.com \
	citizensunited.org \
	city-journal.org \
	cnsnews.com \
	collective-evolution.com &
python scrape.py \
	commentarymagazine.com \
	conservativedailypost.com \
	conservativereview.com \
	consortiumnews.com \
	corbettreport.com \
	cosmicscientist.com \
	countercurrents.org \
	counterinformation.wordpress.com \
	counterjihad.com \
	counterpunch.org \
	dailycaller.com \
	dailymail.co.uk \
	dailyoccupation.com \
	dailysignal.com \
	dailystormer.com \
	darkmoon.me \
	darkpolitricks.com \
	davidstockmanscontracorner.com \
	dcclothesline.com \
	dcleaks.com \
	defenddemocracy.press \
	defensenews.com \
	dennismichaellynch.com \
	disclose.tv \
	disclosuremedia.net \
	dreamlandresort.com \
	drudgereport.com \
	educateinspirechange.org \
	educate-yourself.org \
	endingthefed.com \
	endoftheamericandream.com \
	endtime.com \
	eutimes.net \
	eutopia.buzz \
	ewao.com &
python scrape.py \
	eyeopening.info \
	familysecuritymatters.org \
	fbi.gov \
	fellowshipoftheminds.com \
	filmsforaction.org \
	floridasunpost.com \
	foreignpolicyjournal.com \
	fourwinds10.net \
	freebeacon.com \
	freedomoutpost.com \
	freedomworks.org \
	frontpagemag.com \
	gaia.com \
	galacticconnection.com \
	gangstergovernment.com \
	gatesofvienna.net \
	geopolmonitor.com \
	globalresearch.ca \
	godlikeproductions.com \
	govtslaves.info \
	greanvillepost.com \
	guccifer2.wordpress.com \
	haaretz.com \
	hangthebankers.com \
	healthnutnews.com \
	heartland.org \
	henrymakow.com \
	heresyblog.net \
	heritage.org \
	heterodoxacademy.org &
python scrape.py \
	hiddenamericans.com \
	hotair.com \
	humansarefree.com \
	ihavethetruth.com \
	ilovemyfreedom.org \
	in5d.com \
	informationclearinghouse.info \
	infowars.com \
	intellihub.com \
	intersectionproject.eu \
	intrepidreport.com \
	investmentresearchdynamics.com \
	investmentwatchblog.com \
	jackpineradicals.com \
	jamesrgrangerjr.com \
	jewsnews.co.il \
	jihadwatch.org \
	journal-neo.org &
python scrape.py \
	judicialwatch.org \
	katehon.com \
	katehon.org \
	kingworldnews.com \
	lewrockwell.com \
	libertyblitzkrieg.com \
	libertywritersnews.com \
	lifenews.com \
	lifezette.com \
	makeamericagreattoday.com \
	mediaite.com \
	memoryholeblog.com \
	mintpressnews.com \
	moonofalabama.org \
	nakedcapitalism.com \
	nationalreview.com \
	naturalblaze.com \
	naturalnews.com \
	newatlas.com \
	newcoldwar.org &
python scrape.py \
	newstarget.com \
	news.usni.org \
	newswithviews.com \
	nowtheendbegins.com \
	nutritionfacts.org \
	observer.com \
	off-guardian.org \
	oftwominds.com \
	oilgeopolitics.net \
	opednews.com \
	orientalreview.org \
	pamelageller.com \
	patriotrising.com \
	paulcraigroberts.org \
	peakprosperity.com \
	phibetaiota.net \
	pjmedia.com \
	platosguns.com \
	powerlineblog.com \
	pravdareport.com \
	pravda.ru \
	prepperwebsite.com \
	prisonplanet.com \
	rbth.com \
	readfomag.com \
	readynutrition.com \
	redflagnews.com \
	regated.com \
	rense.com \
	righton.com &
python scrape.py \
	rightwingnews.com \
	rinf.com \
	ronpaulinstitute.org \
	rt.com \
	rumormillnews.com \
	ruptly.tv \
	russia-direct.org \
	russia-insider.com \
	sbir.gov \
	sentinelblog.com \
	sentinel.ht \
	sgtreport.com \
	shadowproof.com \
	shadowstats.com \
	shiftfrequency.com \
	shtfplan.com \
	silentmajoritypatriots.com \
	silverdoctors.com \
	sott.net \
	southfront.org \
	speisa.com \
	sputniknews.com \
	stateofthenation2012.com \
	stevequayle.com \
	stormcloudsgathering.com \
	strategic-culture.org \
	superstation95.com \
	survivopedia.com \
	theamericanmirror.com \
	theantimedia.org \
	theaviationist.com \
	theburningplatform.com \
	thecollegefix.com \
	thecommonsenseshow.com \
	theconservativetreehouse.com \
	thedailybell.com \
	thedailysheeple.com &
python scrape.py \
	theduran.com \
	theearthchild.co.za \
	theeconomiccollapseblog.com \
	theeventchronicle.com \
	thefederalistpapers.org \
	thefreethoughtproject.com \
	thegatewaypundit.com \
	themindunleashed.org \
	thenewsdoctors.com \
	the-newspapers.com \
	therebel.media \
	therightscoop.com \
	therussophile.org \
	thesaker.is \
	thesleuthjournal.com \
	thetruenews.info \
	thetruthseeker.co.uk \
	thirdworldtraveler.com \
	toprightnews.com \
	trueactivist.com \
	truepundit.com \
	trunews.com \
	truthandaction.org \
	truthdig.com \
	truthfeed.com \
	truthkings.com \
	truth-out.org \
	twitchy.com \
	ufoholic.com \
	undergroundworldnews.com &
python scrape.py \
	unz.com \
	usanewshome.com \
	usapoliticsnow.com \
	usasupreme.com \
	usdcrisis.com \
	usslibertyveterans.org \
	vdare.com \
	veteransnewsnow.com \
	veteranstoday.com \
	vigilantcitizen.com \
	viralliberty.com \
	voltairenet.org \
	wakeupthesheep.com \
	wakingtimes.com \
	warisboring.com \
	warontherocks.com \
	washingtonsblog.com \
	wearechange.org \
	weaselzippers.us \
	weeklystandard.com \
	weshapelife.org \
	westernjournalism.com \
	whatdoesitmean.com \
	whatreallyhappened.com \
	wikileaks.com \
	wikileaksdecrypted.com \
	wikileaks.org \
	wikispooks.com \
	wnd.com \
	worldnewspolitics.com \
	worldpoliticsus.com \
	www.fort-russ.com \
	youngcons.com \
	yournewswire.com \
	zerohedge.com &
